#Actividad 2(Valores Nulos)
-------------------------------------

####Angel Rubén Vázquez Rivera
######A01735407

###Importar librerias

In [1]:
import pandas as pd
import numpy as np

###Cargar archivo

In [2]:
data = pd.read_csv("Ventas_totales.csv")
data.head()

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,...,almacen,panaderia,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar,otros
0,01/01/2017,27858.9,27477.3,27858872.08,27591730.13,267141.956,27858872.08,1.023010e+07,6864575.384,9047205.493,...,6705475.318,9.459063e+05,2880656.169,2606192.942,1.050314e+06,340777.3882,4397543.671,772371.8476,1838507.096,2806660.309
1,01/02/2017,25994.2,25223.4,25994200.17,25749179.40,245020.769,25994200.17,9.719067e+06,6438494.011,8309150.301,...,6576624.803,9.256186e+05,2855639.900,2600083.591,1.026167e+06,328288.6951,4053283.771,672290.5165,1257661.903,2354084.901
2,01/03/2017,27780.0,26334.3,27780006.52,27472228.72,307777.804,27780006.52,1.024444e+07,6908522.962,8845010.494,...,7437264.174,1.016148e+06,3188259.169,2824976.726,1.075526e+06,353335.1548,4354197.611,667696.6653,1305674.917,2266189.277
3,01/04/2017,29134.3,27045.9,29134272.22,28827479.49,306792.733,29134272.22,1.031263e+07,7454251.800,9458166.682,...,8211244.093,1.132396e+06,3257140.159,3006158.760,1.037213e+06,359694.4537,4355706.646,838948.2458,1535726.345,2146755.887
4,01/05/2017,27969.0,25631.9,27969004.68,27569311.41,399693.262,27969004.68,1.014761e+07,6735747.319,9220929.862,...,7651058.084,1.033082e+06,3232635.767,2799142.123,9.826512e+05,336568.0085,4206101.605,915895.1498,1824462.036,2117971.483

###Revisar la cantidad de valores nulos por columna

In [3]:
#Identificar valores nulos por columna para saber como ir resolviendo los nulos
valoresNulos = data.isnull().sum()
valoresNulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            6
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         1
tarjetas_credito                        7
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 2
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
otros                                   4
dtype: int64

###Eliminar columnas innecesarias

En este caso elimine la utima columna porque no ofrecia algun valor para mi, ademas de no encontrarle mucho sentido

In [4]:
#Eliminar columnas innecesarias
data = data.drop(['otros'], axis=1)
data.head()

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,...,bebidas,almacen,panaderia,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar
0,01/01/2017,27858.9,27477.3,27858872.08,27591730.13,267141.956,27858872.08,1.023010e+07,6864575.384,9047205.493,...,3514467.398,6705475.318,9.459063e+05,2880656.169,2606192.942,1.050314e+06,340777.3882,4397543.671,772371.8476,1838507.096
1,01/02/2017,25994.2,25223.4,25994200.17,25749179.40,245020.769,25994200.17,9.719067e+06,6438494.011,8309150.301,...,3344456.931,6576624.803,9.256186e+05,2855639.900,2600083.591,1.026167e+06,328288.6951,4053283.771,672290.5165,1257661.903
2,01/03/2017,27780.0,26334.3,27780006.52,27472228.72,307777.804,27780006.52,1.024444e+07,6908522.962,8845010.494,...,3290739.324,7437264.174,1.016148e+06,3188259.169,2824976.726,1.075526e+06,353335.1548,4354197.611,667696.6653,1305674.917
3,01/04/2017,29134.3,27045.9,29134272.22,28827479.49,306792.733,29134272.22,1.031263e+07,7454251.800,9458166.682,...,3253288.237,8211244.093,1.132396e+06,3257140.159,3006158.760,1.037213e+06,359694.4537,4355706.646,838948.2458,1535726.345
4,01/05/2017,27969.0,25631.9,27969004.68,27569311.41,399693.262,27969004.68,1.014761e+07,6735747.319,9220929.862,...,2869437.411,7651058.084,1.033082e+06,3232635.767,2799142.123,9.826512e+05,336568.0085,4206101.605,915895.1498,1824462.036

In [5]:
#Identificar valores nulos por columna para revisar si exitieron cambios
valoresNulos = data.isnull().sum()
valoresNulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            6
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         1
tarjetas_credito                        7
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 2
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
dtype: int64

###Tratar los nulos en subtotal_ventas_alimentos_bebidas

Reemplazo todos los nulos por la media de los valores existentes de esa columna, ya que es una buena opcion promediar los costos de las ventas

In [6]:
#Primer metodo de sustitucion de valores nulos
#Sustituir valores nulos con promedio o media
data2 = data.copy()
data2["subtotal_ventas_alimentos_bebidas"] = data2["subtotal_ventas_alimentos_bebidas"].fillna(round(data["subtotal_ventas_alimentos_bebidas"].mean(),1))
data2.head()

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,...,bebidas,almacen,panaderia,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar
0,01/01/2017,27858.9,27477.3,27858872.08,27591730.13,267141.956,27858872.08,1.023010e+07,6864575.384,9047205.493,...,3514467.398,6705475.318,9.459063e+05,2880656.169,2606192.942,1.050314e+06,340777.3882,4397543.671,772371.8476,1838507.096
1,01/02/2017,25994.2,25223.4,25994200.17,25749179.40,245020.769,25994200.17,9.719067e+06,6438494.011,8309150.301,...,3344456.931,6576624.803,9.256186e+05,2855639.900,2600083.591,1.026167e+06,328288.6951,4053283.771,672290.5165,1257661.903
2,01/03/2017,27780.0,26334.3,27780006.52,27472228.72,307777.804,27780006.52,1.024444e+07,6908522.962,8845010.494,...,3290739.324,7437264.174,1.016148e+06,3188259.169,2824976.726,1.075526e+06,353335.1548,4354197.611,667696.6653,1305674.917
3,01/04/2017,29134.3,27045.9,29134272.22,28827479.49,306792.733,29134272.22,1.031263e+07,7454251.800,9458166.682,...,3253288.237,8211244.093,1.132396e+06,3257140.159,3006158.760,1.037213e+06,359694.4537,4355706.646,838948.2458,1535726.345
4,01/05/2017,27969.0,25631.9,27969004.68,27569311.41,399693.262,27969004.68,1.014761e+07,6735747.319,9220929.862,...,2869437.411,7651058.084,1.033082e+06,3232635.767,2799142.123,9.826512e+05,336568.0085,4206101.605,915895.1498,1824462.036

In [7]:
#Identificar valores nulos por columna para revisar si exitieron cambios

valoresNulos = data2.isnull().sum()
valoresNulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           6
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        1
tarjetas_credito                       7
otros_medios                           1
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                1
almacen                                2
panaderia                              1
lacteos                                1
carnes                                 1
verduleria_fruteria                    1
alimentos_preparados_rotiseria         1
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    2
electronicos_articulos_hogar           3
dtype: int64

###Tratar los nulos en salon_ventas, tarjetas_debito y tarejtas_credito

Sustituyo valores nulos por valores no nulos hacia atras backward fill, llegando a esta conclusion porque son datos a los que realmente no puedo aplicar alguna medida de tendencia central, entonces opte por agregarles los valores de los registros anteriores, pues si alguna tarjeta se uso una vez es probeble que se use de nuevo para una nueva compra o transaccion

In [8]:
#Reemplazo los nulos por el valor anterior en el registro en las siguientes 3 columnas
data2["salon_ventas"] = data2["salon_ventas"].fillna(method="bfill")
data2["tarjetas_debito"] = data2["tarjetas_debito"].fillna(method="bfill")
data2["tarjetas_credito"] = data2["tarjetas_credito"].fillna(method="bfill")

In [9]:
#Identificar valores nulos por columna para revisar si exitieron cambios
valoresNulos = data2.isnull().sum()
valoresNulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           1
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                1
almacen                                2
panaderia                              1
lacteos                                1
carnes                                 1
verduleria_fruteria                    1
alimentos_preparados_rotiseria         1
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    2
electronicos_articulos_hogar           3
dtype: int64

###Tratar los nulos en bebidas, panaderia, lacteos, carnes, verduleria_fruteria, alimentos_preparados_rotiseria

Sustituyo valores nulos por sus maximos y minimos registrados en esas columnas, esto basado en el tipo de producto especifico

In [10]:
#Sustituir nulos por maximo de esa columna
data2["bebidas"] = data2["bebidas"].fillna(round(data2["bebidas"].max(),1))

#Sustituir nulos por minimo de esa columna
data2["panaderia"] = data2["panaderia"].fillna(round(data2["panaderia"].min(),1))

#Sustituir nulos por maximo de esa columna
data2["lacteos"] = data2["lacteos"].fillna(round(data2["lacteos"].max(),1))

#Sustituir nulos por minimo de esa columna
data2["carnes"] = data2["carnes"].fillna(round(data2["carnes"].min(),1))

#Sustituir nulos por maximo de esa columna
data2["verduleria_fruteria"] = data2["verduleria_fruteria"].fillna(round(data2["verduleria_fruteria"].max(),1))

#Sustituir nulos por minimo de esa columna
data2["alimentos_preparados_rotiseria"] = data2["alimentos_preparados_rotiseria"].fillna(round(data2["alimentos_preparados_rotiseria"].min(),1))

In [11]:
#Identificar valores nulos por columna para revisar si exitieron cambios
valoresNulos = data2.isnull().sum()
valoresNulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           1
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                2
panaderia                              0
lacteos                                0
carnes                                 0
verduleria_fruteria                    0
alimentos_preparados_rotiseria         0
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    2
electronicos_articulos_hogar           3
dtype: int64

###Tratar los nulos en otros_medios y almacen

Susituyo valores nulos por valores no nulos hacia adelante "forwad fill" ("ffill"), pues tomo el valor despues de mi espacio nulo (solo para utilizar este metodo tambien)

In [12]:
#Reemplazar los nulos por su valor siguiente
data2["otros_medios"] = data2["otros_medios"].fillna(method="ffill")
data2["almacen"] = data2["almacen"].fillna(method="ffill")

In [13]:
#Identificar valores nulos por columna para revisar si exitieron cambios
valoresNulos = data2.isnull().sum()
valoresNulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                0
panaderia                              0
lacteos                                0
carnes                                 0
verduleria_fruteria                    0
alimentos_preparados_rotiseria         0
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    2
electronicos_articulos_hogar           3
dtype: int64

###Tratar los nulos en indumentaria_calzado_textiles_hogar y electronicos_articulos_hogar

Sustituir valores nulos con la mediana

In [14]:
data2["indumentaria_calzado_textiles_hogar"] = data2["indumentaria_calzado_textiles_hogar"].fillna(round(data["indumentaria_calzado_textiles_hogar"].mean(),1))
data2["electronicos_articulos_hogar"] = data2["electronicos_articulos_hogar"].fillna(round(data["electronicos_articulos_hogar"].median(),1))

In [21]:
#Identificar valores nulos por columna para revisar si exitieron cambios
valoresNulos = data2.isnull().sum()
valoresNulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                0
panaderia                              0
lacteos                                0
carnes                                 0
verduleria_fruteria                    0
alimentos_preparados_rotiseria         0
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    0
electronicos_articulos_hogar           0
dtype: int64

###Comprobar que ya no exista nada nulo en el dataframe

In [22]:
valoresNulos = data2.isnull().sum().sum()
valoresNulos

0

###Convertir dataSet sin valores nulos a CSV

In [16]:
#Convertir fataframe a csv
data2.to_csv("infoSinNulos.csv")