#Actividad 1.3
-------------------------------------

####Angel Rubén Vázquez Rivera
######A01735407

###Importar librerias

In [5]:
import pandas as pd

###Cargar archivo

In [6]:
data = pd.read_excel('Inmuebles.xlsx', header=1)
data

,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,1,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19,Carmen
1,2,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
2,3,2004-01-01,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08,Joaquín
3,4,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
4,5,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
...,...,...,...,...,...,...,...,...,...
3332,3333,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3333,3334,2007-04-29,Piso,Alquiler,Girona,55.0,454080.0,NaT,NaN
3334,3335,2007-04-30,Suelo,Venta,Tarragona,78.0,740688.0,NaT,NaN
3335,3336,2007-04-30,Piso,Alquiler,Barcelona,88.0,397408.0,NaT,NaN
3336,3337,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

##Seccion de filtros

###Filtro1. Eliminar la columna Referencia

Solo se elimina la columna de referencias del DataSet

In [7]:
filtro1 = data.drop(columns=['Referencia'], axis=1)
filtro1

,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19,Carmen
1,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
2,2004-01-01,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08,Joaquín
3,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
4,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3333,2007-04-29,Piso,Alquiler,Girona,55.0,454080.0,NaT,NaN
3334,2007-04-30,Suelo,Venta,Tarragona,78.0,740688.0,NaT,NaN
3335,2007-04-30,Piso,Alquiler,Barcelona,88.0,397408.0,NaT,NaN
3336,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

###Guardar en CSV

In [8]:
# Guardar filtro en CSV
filtro1.to_csv("Filtro1.csv")

###Filtro2. Todos las registros de “Fecha Alta : igual a 2007-04-29 00:00:00 y a 2004-01-02 00:00:00

Solo se muestran los registros que coincidan con las fechas buscadas

In [9]:
filtro2 = data.loc[(data['Fecha_Alta'] == '2007-04-29 00:00:00') | (data['Fecha_Alta'] == '2004-01-02 00:00:00')]
filtro2

,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
3,4,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
4,5,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
3331,3332,2007-04-29,Oficina,Venta,Lleida,190.0,1031320.0,NaT,NaN
3332,3333,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3333,3334,2007-04-29,Piso,Alquiler,Girona,55.0,454080.0,NaT,NaN

###Guardar en CSV

In [11]:
filtro2.to_csv("Filtro2.csv")

###Filtro3. Todos los registros de “ Tipo: parking, local, industrial y piso”

Se muestran solo los registros que coincidan con los tipos buscados

In [12]:
filtro3 = data[data['Tipo'].isin(['Parking', 'Local', 'Industrial', 'Piso'])]
filtro3

,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,1,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19,Carmen
1,2,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
3,4,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
5,6,2004-01-03,Industrial,Alquiler,Girona,131.0,953156.0,2004-09-05,Pedro
6,7,2004-01-03,Parking,Alquiler,Tarragona,NaN,406686.0,2004-06-07,Pedro
...,...,...,...,...,...,...,...,...,...
3330,3331,2007-04-27,Local,Venta,Girona,110.0,845790.0,NaT,NaN
3332,3333,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3333,3334,2007-04-29,Piso,Alquiler,Girona,55.0,454080.0,NaT,NaN
3335,3336,2007-04-30,Piso,Alquiler,Barcelona,88.0,397408.0,NaT,NaN
3336,3337,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

###Guardar en CSV

In [13]:
filtro3.to_csv("Filtro3.csv")

###Filtro4. Todos los registros con “Provincia” igual a “Girona” y con “Superficie” mayor a “100”

Solo los registros que coincidan con las condiciones esperadas

In [14]:
filtro4 = data[(data['Provincia'] == 'Girona') & (data['Superficie'] > 100)]
filtro4

,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
1,2,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
3,4,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
5,6,2004-01-03,Industrial,Alquiler,Girona,131.0,953156.0,2004-09-05,Pedro
7,8,2004-01-03,Oficina,Venta,Girona,235.0,2158475.0,2004-10-31,Jesús
10,11,2004-01-04,Oficina,Alquiler,Girona,124.0,627068.0,2004-10-28,Pedro
...,...,...,...,...,...,...,...,...,...
3299,3300,2007-04-12,Local,Alquiler,Girona,156.0,881868.0,NaT,NaN
3303,3304,2007-04-12,Piso,Venta,Girona,128.0,1270400.0,NaT,NaN
3306,3307,2007-04-14,Parking,Venta,Girona,221.0,1533077.0,NaT,NaN
3316,3317,2007-04-20,Casa,Venta,Girona,247.0,1804088.0,NaT,NaN
3330,3331,2007-04-27,Local,Venta,Girona,110.0,845790.0,NaT,NaN

###Guardar en CSV

In [15]:
filtro4.to_csv("Filtro4.csv")

###Filtro5. Todos los registros con “Precio Venta: mayor a 1000,000” o “vendedor” igual a “Carmen o Joaquin”

In [16]:
filtro5 = data[(data['Precio Venta'] > 1000000) | (data['Vendedor'].isin(['Carmen', 'Joaquín']))]
filtro5

,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,1,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19,Carmen
1,2,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
2,3,2004-01-01,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08,Joaquín
7,8,2004-01-03,Oficina,Venta,Girona,235.0,2158475.0,2004-10-31,Jesús
8,9,2004-01-04,Piso,Alquiler,Lleida,108.0,1024380.0,2004-12-28,Jesús
...,...,...,...,...,...,...,...,...,...
3325,3326,2007-04-25,Industrial,Alquiler,Barcelona,296.0,2078216.0,NaT,NaN
3328,3329,2007-04-26,Piso,Venta,Barcelona,264.0,2517504.0,NaT,NaN
3331,3332,2007-04-29,Oficina,Venta,Lleida,190.0,1031320.0,NaT,NaN
3332,3333,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3336,3337,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

###Guardar en CSV

In [17]:
filtro5.to_csv("Filtro5.csv")

###Filtro6. Todos los registros que no sean de “Provincia : Barcelona“

In [18]:
filtro6 = data[data['Provincia'] != 'Barcelona']
filtro6

,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,1,2004-01-01,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19,Carmen
1,2,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
2,3,2004-01-01,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08,Joaquín
3,4,2004-01-02,Parking,Alquiler,Girona,285.0,NaN,2004-04-27,Jesús
4,5,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
...,...,...,...,...,...,...,...,...,...
3331,3332,2007-04-29,Oficina,Venta,Lleida,190.0,1031320.0,NaT,NaN
3332,3333,2007-04-29,Industrial,Alquiler,Lleida,221.0,1450644.0,NaT,NaN
3333,3334,2007-04-29,Piso,Alquiler,Girona,55.0,454080.0,NaT,NaN
3334,3335,2007-04-30,Suelo,Venta,Tarragona,78.0,740688.0,NaT,NaN
3336,3337,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

###Guardar en CSV

In [19]:
filtro6.to_csv("Filtro6.csv")

###Filtro7. Todos los registros que no sean de “Operación: alquiler “ ni “Tipo: oficina“

In [20]:
filtro7 = data[~((data['Operación'] == 'Alquiler') | (data['Tipo'] == 'Oficina'))]
display(filtro7)

,Referencia,Fecha_Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
1,2,2004-01-01,Local,Venta,Girona,185.0,1945424.0,2004-04-19,Pedro
4,5,2004-01-02,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10,María
9,10,2004-01-04,Parking,Venta,Lleida,299.0,2042768.0,2004-10-06,Joaquín
11,12,2004-01-04,Industrial,Venta,Girona,187.0,999328.0,2004-04-05,Carmen
12,13,2004-01-04,Parking,Venta,Barcelona,NaN,2937300.0,2004-11-04,Jesús
...,...,...,...,...,...,...,...,...,...
3328,3329,2007-04-26,Piso,Venta,Barcelona,264.0,2517504.0,NaT,NaN
3329,3330,2007-04-27,Parking,Venta,Barcelona,88.0,612568.0,NaT,NaN
3330,3331,2007-04-27,Local,Venta,Girona,110.0,845790.0,NaT,NaN
3334,3335,2007-04-30,Suelo,Venta,Tarragona,78.0,740688.0,NaT,NaN
3336,3337,2007-04-30,Parking,Venta,Lleida,254.0,2140712.0,NaT,NaN

###Guardar en CSV

In [21]:
filtro7.to_csv("Filtro7.csv")